os:
  - linux
#  - osx

dist:
  - xenial

language: c++

arch:
#  - amd64
#  - arm64
#  - ppc64le
  - s390x

addons:
  apt:
    packages:
      - gdb
      - libclang-common-3.8-dev

compiler:
#  - g++
  - clang

install: skip

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - gdb --ex=r -return-child-result -batch -ex bt --args ./diamond test
#  - lldb --batch --one-line r --one-line-on-crash bt -- ./diamond test
#  - ./diamond test